title: Xuejun's Blog
description: A blog powered by GitHub Pages and Jekyll
theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    disable : true
# trigger rebuild
